### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by inklit** [justync7/MinimalPeripherals#1]
This happens on 1.10.2 when you do peripheral.playNote(15,20)
http://hastebin.com/cabevugaru.md

**Comment by Lustyn** [comment]
I'll look at it tomorrow. I found this when testing earlier but it didn't
seem to cause a crash. I thought I fixed it, but maybe not.

**Comment by inklit** [comment]
It takes a ton of server ticktime, not an immediate crash but the server watchdog kills the server while it's frozen.

**Comment by Lustyn** [comment]
Ah. Although, you're using playNote incorrectly anyways so if you use it in
the correct range for the instrument it will work fine. ;P

**Comment by columna1** [comment]
Didn't seem to work correctly. Playnote didn't play noteblock sounds. which is why I decided to try something out of the instrument range.

**Comment by Lustyn** [comment]
Fixed in a7b89c1bfd1f0adf72c8d6258b9192f004a7cf65
