### ISSUE TITLE
"leave" event keeps getting fired in a loop

### ISSUE THREAD

**Issue by Ale32bit** [justync7/MinimalPeripherals#3]
Normally, when a player leaves (I'll refer to it as "glitched player"), chatboxes detect the "leave" event only once, but sometime the event gets repeated each x seconds until the "glitched" player joins or the server restarts.

I hope this is fixable, because it's just annoying to see logs filled with "Steve left the game"

**Comment by Lustyn** [comment]
I haven’t looked into it yet but this seems like an issue Sponge would
cause. I’ve never had this happen in the past.
